import secrets
from enum import Enum
from typing import Any, Dict, List, Optional, Union

import orjson
from pydantic import BaseModel, Field

class PropertyKind(Enum):
    ENTITY = "ENTITY"
    CAS_POINTER = "CAS_POINTER"
    META_FIELD = "META_FIELD"
    META_ENTITY = "META_ENTITY"
    LITERAL = "LITERAL"


class ActionSource(Enum):
    ENTITY = "ENTITY"
    LITERAL = "LITERAL"


class DataFormat(Enum):
    JSON = "JSON"


class ActionProperty(BaseModel):
    name: str
    kind: PropertyKind
    data_format: DataFormat = DataFormat.JSON
    value: Union[str, Dict, List]


class Action(BaseModel):
    kind: str
    properties: List[ActionProperty]
    wildcard_triggers: Optional[List[str]] = []

    @classmethod
    def from_bytes(cls, data: bytes) -> "Action":
        return cls(**orjson.loads(data))

    def to_bytes(self) -> bytes:
        return orjson.dumps(self.dict())


def autogenerated_jid():
    return secrets.token_hex(16)


class ActionTrigger(BaseModel):
    meta: Dict[str, Any] = {}
    action_source: ActionSource
    action: Union[str, Action]
    jid: str = Field(default_factory=autogenerated_jid)

    @classmethod
    def from_bytes(cls, data: bytes) -> "Action":
        return cls(**orjson.loads(data))

    def to_bytes(self) -> bytes:
        return orjson.dumps(self.dict())


class ActionResult(BaseModel):
    success: bool

    def to_bytes(self) -> bytes:
        return orjson.dumps(self.dict())
